fixtures:
  repositories:
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "translate": 
      "repo": "https://github.com/puppetlabs/puppetlabs-translate"
  symlinks:
    "apt": "#{source_dir}"
