version: '3'
services:
  dev:
    image: idevlab/docker-pintos:latest
    container_name: pintos-dev
    volumes:
      - pintos-volume:/home/vagrant/code
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

volumes:
  pintos-volume:
    external: true