version: '3'
services:
  dev:
    build: .
    container_name: pintos-dev
    volumes:
      - pintos-volume:/root/code
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - 5000:5000

volumes:
  pintos-volume:
    external: true